# Thanks https://realpython.com/python-project-documentation-with-mkdocs/#adapt-your-project-settings-file
# Thanks https://www.mkdocs.org/user-guide/configuration/

site_name: Wattpad
repo_url: https://github.com/TheOnlyWayUp/wattpad/
site_url: https://wattpad.rambhat.la
site_author: TheOnlyWayUp

strict: true


theme:
  name: "material"
  favicon: "wattpad.svg"

plugins:
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.snippets:
      check_paths: true



watch:
  - docs
  - mkdocs.yml
  - src
  - README.md

nav:
  - Home: index.md
  - quickstart.ipynb
  - Memory Efficiency and Caching: memory-efficiency.ipynb
  - Synchronous and Asynchronous Usage: sync-and-async.ipynb
  - API Reference:
    - User: reference/user.md
    - Story: reference/story.md
    - Utilities: reference/utils.md
    - Models:
      - Models: reference/models.md
      - Types: reference/model_types.md
